### ISSUE TITLE
Error In logs

### ISSUE THREAD

**Issue by ghost** [rekcah-pavi/javes#17]
2020-12-13T10:00:44.421857+00:00 app[worker.1]: Traceback (most recent call last):
2020-12-13T10:00:44.421860+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
2020-12-13T10:00:44.421861+00:00 app[worker.1]:     return _run_code(code, main_globals, None,
2020-12-13T10:00:44.421861+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
2020-12-13T10:00:44.421862+00:00 app[worker.1]:     exec(code, run_globals)
2020-12-13T10:00:44.421863+00:00 app[worker.1]:   File "/root/userbot/userbot/__main__.py", line 57, in <module>
2020-12-13T10:00:44.421863+00:00 app[worker.1]:     javes.loop.run_until_complete(a())
2020-12-13T10:00:44.421864+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
2020-12-13T10:00:44.421864+00:00 app[worker.1]:     return future.result()
2020-12-13T10:00:44.421865+00:00 app[worker.1]:   File "/root/userbot/userbot/__main__.py", line 45, in a
2020-12-13T10:00:44.421865+00:00 app[worker.1]:     import_module(f"userbot.modules.{cr}")
2020-12-13T10:00:44.421866+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
2020-12-13T10:00:44.421866+00:00 app[worker.1]:     return _bootstrap._gcd_import(name[level:], package, level)
2020-12-13T10:00:44.421867+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2020-12-13T10:00:44.421867+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2020-12-13T10:00:44.421867+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2020-12-13T10:00:44.421868+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
2020-12-13T10:00:44.421868+00:00 app[worker.1]:   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
2020-12-13T10:00:44.421869+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2020-12-13T10:00:44.421869+00:00 app[worker.1]:   File "/root/userbot/userbot/modules/alive.py", line 9, in <module>
2020-12-13T10:00:44.421870+00:00 app[worker.1]:     import heroku3
2020-12-13T10:00:44.421870+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/site-packages/heroku3/__init__.py", line 27, in <module>
2020-12-13T10:00:44.421871+00:00 app[worker.1]:     from .core import from_key
2020-12-13T10:00:44.421871+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/site-packages/heroku3/core.py", line 10, in <module>
2020-12-13T10:00:44.421872+00:00 app[worker.1]:     from .api import Heroku
2020-12-13T10:00:44.421872+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/site-packages/heroku3/api.py", line 11, in <module>
2020-12-13T10:00:44.421872+00:00 app[worker.1]:     from .helpers import is_collection
2020-12-13T10:00:44.421873+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/site-packages/heroku3/helpers.py", line 12, in <module>
2020-12-13T10:00:44.421873+00:00 app[worker.1]:     from dateutil.parser import parse as parse_datetime
2020-12-13T10:00:44.421874+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/site-packages/dateutil/parser.py", line 158
2020-12-13T10:00:44.421874+00:00 app[worker.1]:     l.append("%s=%s" % (attr, `value`))
2020-12-13T10:00:44.421874+00:00 app[worker.1]:                               ^
2020-12-13T10:00:44.421875+00:00 app[worker.1]: SyntaxError: invalid syntax
2020-12-13T10:00:44.902732+00:00 heroku[worker.1]: Process exited with status 1
2020-12-13T10:00:44.947979+00:00 heroku[worker.1]: State changed from up to crashed
2020-12-13T10:00:44.951225+00:00 heroku[worker.1]: State changed from crashed to starting

**Comment by ghost** [comment]
after it imported 4th plugin
